---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: kcc-demo-pipeline
description: main
serialPipeline:
 stages:
 - targetId: qsprod
   profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsprod
description: production cluster
gke:
 cluster: projects/goog-renewing-grackle/locations/europe-north1-a/clusters/kcc
