apiVersion: skaffold/v2beta16
kind: Config
requires:
- configs: []
  git:
    repo: https://github.com/kesokaj/gcp-kcc-demo.git
    path: /skaffold.yaml
    ref: master
    sync: true
deploy:
  statusCheckDeadlineSeconds: 60
  kubectl:
    manifests:
      - k8s/*.yaml
