---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kcc-demo-svc
  namespace: kcc-deploy
spec:
  member: serviceAccount:kcc-demo-svc@<PROJECT_ID>.iam.gserviceaccount.com
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/<PROJECT_ID>
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: <PROJECT_ID>
  name: kcc-demo-svc
  namespace: kcc-deploy
spec:
  displayName: KCC Demo Service-account
