---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "true"
  name: goog-renewing-grackle-kcc-demo
  namespace: kcc-deploy
spec:
  versioning:
    enabled: true
  uniformBucketLevelAccess: false
  location: eu
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucketAccessControl
metadata:
  name: bucket-acl
  namespace: kcc-deploy
spec:
  bucketRef:
    name: goog-renewing-grackle-kcc-demo
  entity: allAuthenticatedUsers
  role: READER  
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageNotification
metadata:
  name: bucket-to-pubsub
  namespace: kcc-deploy
spec:
  bucketRef:
    name: goog-renewing-grackle-kcc-demo
  payloadFormat: JSON_API_V1
  topicRef:
    name: pubsub-kcc-demo
  eventTypes:
    - "OBJECT_ARCHIVE"
    - "OBJECT_DELETE"
    - "OBJECT_FINALIZE"
    - "OBJECT_METADATA_UPDATE"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: bucket-to-pubsub-policy
  namespace: kcc-deploy
spec:
  member: serviceAccount:service-317432507526@gs-project-accounts.iam.gserviceaccount.com
  role: roles/pubsub.publisher
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: pubsub-kcc-demo  
